on:
  push:
    branches:
      - main
  pull_request:
name: ci
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: npm run start
        env:
          CF_API_TOKEN: 951I9Ajl9arhs8pnJ6Byq8Ovc-lpJ-z2ZZNg-B9q
          CF_ACCOUNT_ID: 26f20451923581330999630486311463
